run:
  go: 1.19
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl # For finding code clones.
    - errcheck # For checking for unchecked errors.
    - exportloopref
    - funlen
    - goconst # For finding repeated strings that could be replaced by a constant.
    - gocyclo # For calculating cyclomatic complexities.
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign # For detecting ineffectual assignments.
    - lll
    - misspell # For correcting commonly misspelled English words.
    - nakedret
    - noctx
    - nolintlint
    - prealloc # For finding slice declarations that could potentially be preallocated.
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert # For identifying unnecessary type conversions.
    - unparam # For finding unused function parameters.
    - unused # For finding unused code.
    - varcheck
    - whitespace

  # don't enable:
  # - asciicheck
  # - scopelint
  # - gocritic
  # - gochecknoglobals
  # - gochecknoinits
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - revive
  # - wsl
