version: "3"
services:

  go_db_app:
    container_name: go_db_app
    build: .
    tty: true
    volumes:
      - .:/go/src/work
    networks:
      - container-link

  go_db_pgsql:
    container_name: go_db_pgsql
    image: postgres:14.4-alpine3.16
    volumes:
      - "./_local/pgsql/setup/db:/docker-entrypoint-initdb.d"
      - "./_local/pgsql/setup/table:/docker-entrypoint-initdb.d/ddl"
      - ./_local/pgsql/storage:/var/lib/pgsql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=exampleuser
      - POSTGRES_PASSWORD=examplepasswd
      - TZ=Asia/Tokyo
    networks:
      - container-link

  go_db_pgadmin:
    container_name: go_db_pgadmin
    image: dpage/pgadmin4:6
    volumes:
      - "./_local/pgadmin:/var/lib/pgadmin"
    environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
        PGADMIN_DEFAULT_PASSWORD: pgadminpasswd
    ports:
      - 8888:80
    hostname: pgadmin4
    depends_on:
      - go_db_pgsql
    networks:
      - container-link

  go_db_mysql:
    container_name: go_db_mysql
    image: mysql:8
    volumes:
      - "./_local/mysql/storage:/var/lib/mysql"
      - "./_local/mysql/setup/conf:/etc/mysql/conf.d"
      - "./_local/mysql/setup/db:/docker-entrypoint-initdb.d"
      - "./_local/mysql/setup/table:/docker-entrypoint-initdb.d/ddl"
    environment:
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepasswd
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - TZ=Asia/Tokyo
    networks:
      - container-link

  go_db_phpmyadmin:
    container_name: go_db_phpmyadmin
    image: phpmyadmin/phpmyadmin
    volumes:
      - "./_local/phpmyadmin/setup/conf/upload.ini:/usr/local/etc/php/conf.d/upload.ini"
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOSTS=go_db_mysql
    ports:
      - 8880:80
    depends_on:
      - go_db_mysql
    networks:
      - container-link

networks:
  # Prevent generating "default" network automatically.
  default:
    external: true
    name: bridge
  # Network segment of inter-container communication.
  container-link:
    name: go_db_network
