version: "3"
services:
  go_rdb_app:
    container_name: go_rdb_app
    build: .
    tty: true
    volumes:
      - .:/go/src/work
    networks:
      - container-link
  go_rdb_db:
    container_name: go_rdb_db
    image: mysql:5.7.25
    volumes:
      - "./local/mysql/storage:/var/lib/mysql"
      - "./local/mysql/setup/conf:/etc/mysql/conf.d"
      - "./local/mysql/setup/entrypoint:/docker-entrypoint-initdb.d"
      - "./local/mysql/setup/ddl:/docker-entrypoint-initdb.d/ddl"
    # The following is the DB connection info for a local env.
    # Never use the following in your production env.
    environment:
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepasswd
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - TZ=Asia/Tokyo
    networks:
      - container-link
  go_rdb_phpmyadmin:
    container_name: go_rdb_phpmyadmin
    image: phpmyadmin/phpmyadmin
    volumes:
      - "./local/phpmyadmin/setup/conf/upload.ini:/usr/local/etc/php/conf.d/upload.ini"
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOSTS=go_rdb_db
    links:
      - go_rdb_db
    ports:
      - 13902:80
    networks:
      - container-link

networks:
  # Prevent generating "default" network automatically
  default:
    external:
      name: bridge
  # Network segment of inter-container communication
  container-link:
    name: go_rdb_network
